services:
  pki-2fa-app:
    build: .
    container_name: pki-2fa-app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./keys:/app/keys   # mount keys folder
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: always
