version: "3.9"
services:
  pki-2fa-app:
    build: .
    container_name: pki-2fa-app
    ports:
      - "8000:8000"
    volumes:
      - ./data/cron.log:/var/log/cron.log
      - ./data:/app/data   # optional: persist app state
